version: "3"
services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 5000:8000
    networks:
     - slproposals
    volumes:
      - ./backend:/backend

volumes:
  backend:
    driver: local
