version: "3"
services:
  backend:
    build:
      context: ./backend
    ports:
      - 5000:5000
    volumes:
      - ./backend:/backend_code
    networks:
      - slproposals_docker_network
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: casper
      MONGO_INITDB_ROOT_PASSWORD: meow
    ports:
      - 27017:27017
    networks:
      - slproposals_docker_network
    volumes:
      - './db_data:/data/db'

  frontend:
    build:
      context: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/frontend_code
    networks:
      - slproposals_docker_network
    depends_on:
      - backend

volumes:
  backend:
    driver: local
  db_data:
    driver: local
  frontend:
    driver: local

networks:
  slproposals_docker_network:
    driver: bridge