version: "3"
services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 5000:8000
    networks:
     - slproposals
    volumes:
      - ./backend:/backend
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    env_file:
      - ./.env
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: casper
      MONGO_INITDB_ROOT_PASSWORD: meow
      MONGO_INITDB_DB: slproposals
    ports:
      - 27017:27017
    networks:
      - slproposals
    volumes:
      - './db_data:/data/db'
      - './db_config:/data/configdb'
      - './docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro'

networks:
  slproposals:
    driver: bridge

volumes:
  backend:
    driver: local
  db_data:
    driver: local
  db_config:
    driver: local
  docker-entrypoint-initdb.d:
    driver: local