version: "3"
services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - ./backend:/backend

volumes:
  backend:
    driver: local