version: "3"
services:
  backend:
    build:
      context: ./backend
    ports:
      - 5000:5000
    volumes:
      - ./backend:/backend_code
    networks:
      - slproposals_docker_network

  frontend:
    build:
      context: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/frontend_code
    networks:
      - slproposals_docker_network
    depends_on:
      - backend

volumes:
  backend:
    driver: local
  frontend:
    driver: local

networks:
  slproposals_docker_network:
    driver: bridge
