version: "3"
services:
  backend:
    volumes:
      - ./backend/src:/code/src
    build:
      context: ./backend
    ports:
      - 5000:5000
    networks:
      - slproposals_docker_network

  frontend:
    build:
      context: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src:/code/src
    networks:
      - slproposals_docker_network
    depends_on:
      - backend
    environment:
      - WATCHPACK_POLLING=true

volumes:
  backend:
  frontend:

networks:
  slproposals_docker_network: