# host frontend on AWS Amplify
# host backend and db on ec2

name: Deployment from Github to AWS
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest repo
        uses: actions/checkout@main
        
      - name: Generate deployment package
        run: zip -r *
        
      - name: Get timestamp
        uses: gerred/actions/current-time@master
        id: current-time
        
      - name: Format timestamp
        uses: frabert/replace-string-action@master
        id: format-time
        with:
          pattern: '[:\.]+'
          string: "${{ steps.current-time.outputs.time }}"
          replace-with: '-'
          flags: 'g'
      
      - name: Deploy slproposals to EC2
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ec2-3-110-177-25.ap-south-1.compute.amazonaws.com
          REMOTE_USER: ec2-user
          SOURCE: /slproposals.zip
          TARGET: /home/ec2-user
