# host frontend on AWS Amplify
# host backend and db on ec2

name: Deployment from Github to AWS
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest repo
        uses: actions/checkout@main
        
      - name: Generate deployment package
        run: zip -r deploy.zip * -x "**node_modules**"
        run: echo 'Meow' && echo ls &&  echo pwd
        
      - name: Get timestamp
        uses: gerred/actions/current-time@master
        id: current-time
        
      - name: Format timestamp
        uses: frabert/replace-string-action@master
        id: format-time
        with:
          pattern: '[:\.]+'
          string: "${{ steps.current-time.outputs.time }}"
          replace-with: '-'
          flags: 'g'
      
      - name: Deploy to EBS
        uses: einaregilsson/beanstalk-deploy@v14
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRECT_ACCESS_KEY }}
          application_name: slproposals
          environment_name: Slproposals-env
          version_label: "slproposals-${{ steps.format-time.outputs.replaced }}"
          region: ap-south-1
          deployment_package: deploy.zip
