# host frontend on AWS Amplify
# host backend and db on ec2

name: Deployment from Github to AWS
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest repo
        uses: actions/checkout@main
        
      - name: Generate deployment package
        run: zip -r backend.zip backend docker-entrypoint-initdb.d docker-compose.yaml * -x "**node_modules**"
        
      - name: my-test
        run: echo 'Meow' && ls && pwd
        
      - name: Get timestamp
        uses: gerred/actions/current-time@master
        id: current-time
        
      - name: Format timestamp
        uses: frabert/replace-string-action@master
        id: format-time
        with:
          pattern: '[:\.]+'
          string: "${{ steps.current-time.outputs.time }}"
          replace-with: '-'
          flags: 'g'
      
      - name: Deploy backend to EC2
        uses: burnett01/rsync-deployments@5.1
        env:
          path: src/
          remote_key: ${{ secrets.EC2_SSH_KEY }}
          remote_host: ${{ secrets.HOST_DNS }}
          remote_user: ${{ secrets.USERNAME }}
          remote_path: /var/www/html/
          rsh: ls && echo meow && pwd