name: Deployment from Github to AWS
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest repo
        uses: actions/checkout@main
        
      - name: Generate FRONTEND deployment package
        run: cd frontend
        run: zip slproposals-frontend.zip -r -m *

      - name: Generate BACKEND deployment package
        run: zip slproposals-backend.zip -r -m backend
        
      - name: Get timestamp
        uses: gerred/actions/current-time@master
        id: current-time
        
      - name: Format timestamp
        uses: frabert/replace-string-action@master
        id: format-time
        with:
          pattern: '[:\.]+'
          string: "${{ steps.current-time.outputs.time }}"
          replace-with: '-'
          flags: 'g'
      
      - name: Deploy slproposals-frontend to EC2
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ec2-13-235-69-76.ap-south-1.compute.amazonaws.com
          REMOTE_USER: ec2-user
          SOURCE: /frontend/slproposals-frontend.zip
          TARGET: /home/ec2-user

      - name: Deploy slproposals-backend to EC2 
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ec2-13-232-1-148.ap-south-1.compute.amazonaws.com
          REMOTE_USER: ec2-user
          SOURCE: /slproposals-backend.zip
          TARGET: /home/ec2-user